// Generated by gencpp from file light_robot/WordCount.msg
// DO NOT EDIT!


#ifndef LIGHT_ROBOT_MESSAGE_WORDCOUNT_H
#define LIGHT_ROBOT_MESSAGE_WORDCOUNT_H

#include <ros/service_traits.h>


#include <light_robot/WordCountRequest.h>
#include <light_robot/WordCountResponse.h>


namespace light_robot
{

struct WordCount
{

typedef WordCountRequest Request;
typedef WordCountResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WordCount
} // namespace light_robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::light_robot::WordCount > {
  static const char* value()
  {
    return "58903d21a3264f3408d79ba79e9f7c7e";
  }

  static const char* value(const ::light_robot::WordCount&) { return value(); }
};

template<>
struct DataType< ::light_robot::WordCount > {
  static const char* value()
  {
    return "light_robot/WordCount";
  }

  static const char* value(const ::light_robot::WordCount&) { return value(); }
};


// service_traits::MD5Sum< ::light_robot::WordCountRequest> should match 
// service_traits::MD5Sum< ::light_robot::WordCount > 
template<>
struct MD5Sum< ::light_robot::WordCountRequest>
{
  static const char* value()
  {
    return MD5Sum< ::light_robot::WordCount >::value();
  }
  static const char* value(const ::light_robot::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::light_robot::WordCountRequest> should match 
// service_traits::DataType< ::light_robot::WordCount > 
template<>
struct DataType< ::light_robot::WordCountRequest>
{
  static const char* value()
  {
    return DataType< ::light_robot::WordCount >::value();
  }
  static const char* value(const ::light_robot::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::light_robot::WordCountResponse> should match 
// service_traits::MD5Sum< ::light_robot::WordCount > 
template<>
struct MD5Sum< ::light_robot::WordCountResponse>
{
  static const char* value()
  {
    return MD5Sum< ::light_robot::WordCount >::value();
  }
  static const char* value(const ::light_robot::WordCountResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::light_robot::WordCountResponse> should match 
// service_traits::DataType< ::light_robot::WordCount > 
template<>
struct DataType< ::light_robot::WordCountResponse>
{
  static const char* value()
  {
    return DataType< ::light_robot::WordCount >::value();
  }
  static const char* value(const ::light_robot::WordCountResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LIGHT_ROBOT_MESSAGE_WORDCOUNT_H
